
[package]
name = "snake"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/Aceeri/amethyst", commit = "037cd79cc217124e94a88872bdeb1c4127ffb542", branch = "clean" }
specs = "0.9.2"
rand = "0.3.15"
